# Generated by Django 3.1.2 on 2020-11-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_record_for_final_calculation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
