# Generated by Django 3.1.2 on 2020-11-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_auto_20201128_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
