# Generated by Django 3.1.2 on 2020-11-28 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0003_auto_20201128_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(default='Task1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
