# Generated by Django 3.1.2 on 2020-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message_app', '0004_auto_20201126_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmessage',
            name='profile',
        ),
    ]
