# Generated by Django 3.1.2 on 2020-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message_app', '0006_replymessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmessage',
            name='msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='Message_app.inboxmessage'),
        ),
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
    ]
