# Generated by Django 3.1.2 on 2020-11-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message_app', '0007_auto_20201127_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmessage',
            name='msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='Message_app.inboxmessage'),
        ),
    ]
