# Generated by Django 3.1.2 on 2020-11-21 02:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=50)),
                ('ps', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('display_status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-num',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_amount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('display_choice', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], default='show', max_length=6)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount_per_unit', models.FloatField(default=0.0)),
                ('total_discount', models.FloatField(default=0.0)),
                ('total_price', models.FloatField()),
                ('total_purchase', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('sell_status', models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ShadeNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shade_num', models.PositiveIntegerField(default=0, unique=True)),
                ('started', models.DateTimeField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard_app.customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
