# Generated by Django 3.1.2 on 2020-11-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_app', '0002_auto_20201121_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_purchase',
        ),
    ]
