# Generated by Django 3.1.2 on 2020-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard_app', '0003_auto_20201122_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadeno',
            name='shade_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
