# Generated by Django 3.1.2 on 2020-11-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackUpData',
        ),
    ]
