# Generated by Django 3.1.2 on 2020-11-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_inventory_app', '0002_delete_backupdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='qty_for_avg',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_price',
        ),
    ]
