# Generated by Django 3.1.2 on 2020-11-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_inventory_app', '0003_auto_20201122_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='import_history',
        ),
    ]
