# Generated by Django 3.1.2 on 2020-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0006_auto_20201124_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogoutlog',
            name='log_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginlogoutlog',
            name='login',
            field=models.BooleanField(default=True),
        ),
    ]
