# Generated by Django 3.1.2 on 2020-11-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0007_auto_20201124_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLogoutLog',
        ),
    ]
