# Generated by Django 3.1.2 on 2020-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0008_delete_loginlogoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
